---
- name: Add deadsnakes PPA for Python 3.12
 apt_repository:
   repo: ppa:deadsnakes/ppa
   state: present
   update_cache: yes
 become: true
 
- name: Config random_c2_profile/Pipfile
 template:
   src: Pipfile.j2 
   dest: /opt/random_c2_profile/Pipfile
   owner: root
   group: root
   mode: '0644'

- name: Set up Python environment with pipenv
 command:
   cmd: pipenv --python 3.12
   chdir: /opt/random_c2_profile
 register: pipenv_setup

- name: Install dependencies with pipenv  
 command:
   cmd: pipenv install
   chdir: /opt/random_c2_profile
 register: pipenv_install

- name: Run the Python script using pipenv run
 command:
   cmd: pipenv run python random_c2profile.py
   chdir: /opt/random_c2_profile
 register: generate_profile

- name: Find the generated profile file
 find:
   paths: /opt/random_c2_profile/output
   patterns: "*.profile"
 register: profile_file

- name: Move profile file to /opt/malleable.profile
 command:
   cmd: "mv {{ profile_file.files[0].path }} /opt/malleable.profile"
 when: profile_file.files | length > 0
