---
all:
  hosts:
    azure_vm:
      ansible_host: "{{ lookup('env', 'VM_IP') }}"
      ansible_user: "{{ lookup('env', 'VM_USER') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') }}"
      ansible_python_interpreter: /usr/bin/python3