---
- name: Install Certbot via snap
  snap:
    name: certbot
    classic: yes
    state: present

- name: Get FQDN from Terraform output
  command: terraform output -raw fqdn
  register: fqdn_output
  changed_when: false
  args:
    chdir: "{{ playbook_dir }}/../../Terraform-Pack"

- name: Configure SSL with Certbot
  command: /snap/bin/certbot certonly -d {{ fqdn_output.stdout }} --nginx --register-unsafely-without-email --agree-tos --non-interactive
  register: certbot_result
  changed_when: certbot_result.rc == 0