---
- name: Export certificate to PKCS12
  command: >
    openssl pkcs12 -inkey /etc/letsencrypt/live/{{ lookup('env', 'VM_FQDN') }}/privkey.pem 
    -in /etc/letsencrypt/live/{{ lookup('env', 'VM_FQDN') }}/fullchain.pem 
    -export -out /opt/{{ lookup('env', 'KEYSTORE_FILE') }}.pkcs12
    -passout pass:"{{ lookup('env', 'KEYSTORE_PASS') }}"
  args:
    creates: "/opt/{{ lookup('env', 'KEYSTORE_FILE') }}.pkcs12"

- name: Import PKCS12 to Java keystore
  command: >
    keytool -importkeystore 
    -srckeystore /opt/{{ lookup('env', 'KEYSTORE_FILE') }}.pkcs12 
    -srcstoretype pkcs12 
    -destkeystore /opt/{{ lookup('env', 'KEYSTORE_FILE') }}.store
    -srcstorepass "{{ lookup('env', 'KEYSTORE_PASS') }}"
    -deststorepass "{{ lookup('env', 'KEYSTORE_PASS') }}"
    -noprompt
  args:
    creates: "/opt/{{ lookup('env', 'KEYSTORE_FILE') }}.store"
