---
- name: Export certificate to PKCS12
  command: >
    openssl pkcs12 -inkey /etc/letsencrypt/live/{{ lookup('env', 'VM_FQDN') }}/privkey.pem 
    -in /etc/letsencrypt/live/{{ lookup('env', 'VM_FQDN') }}/fullchain.pem 
    -export -out $HOME/mykey.pkcs12
  args:
    creates: "$HOME/mykey.pkcs12"

- name: Import PKCS12 to Java keystore
  command: >
    keytool -importkeystore 
    -srckeystore $HOME/mykey.pkcs12 
    -srcstoretype pkcs12 
    -destkeystore $HOME/mykey.store
  args:
    creates: "$HOME/mykey.store"