---
- name: Export certificate to PKCS12
  command: >
    openssl pkcs12 -inkey /etc/letsencrypt/live/{{ lookup('env', 'VM_FQDN') }}/privkey.pem 
    -in /etc/letsencrypt/live/{{ lookup('env', 'VM_FQDN') }}/fullchain.pem 
    -export -out /opt/mykey.pkcs12
    -passout pass:"skyfall"
  args:
    creates: "/opt/mykey.pkcs12"

- name: Import PKCS12 to Java keystore
  command: >
    keytool -importkeystore 
    -srckeystore /opt/mykey.pkcs12 
    -srcstoretype pkcs12 
    -destkeystore /opt//mykey.store
    -srcstorepass "skyfall"
    -deststorepass "skyfall"
    -noprompt
  args:
    creates: "/opt/mykey.store"
