---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Perform system upgrade
  apt:
    upgrade: yes
    update_cache: yes

- name: Perform distribution upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Remove unused packages (autoremove)
  apt:
    autoremove: yes